# Generated by Django 4.2.9 on 2024-01-24 02:00

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=froala_editor.fields.FroalaField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='stderr',
            field=froala_editor.fields.FroalaField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='stdout',
            field=froala_editor.fields.FroalaField(default=''),
        ),
    ]
