# Generated by Django 4.2.9 on 2024-01-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0003_alter_problem_description_alter_testcase_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
