# Generated by Django 4.2.9 on 2024-01-26 23:02

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_alter_problem_description_alter_testcase_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=froala_editor.fields.FroalaField(default=''),
        ),
    ]
